### PR TITLE
Hb finegrained runtime cello

### PR DESCRIPTION
**Pull request by mrutt92**

### CODE REVIEW

**Review by yodada — APPROVED** [review]
Cool! Just wanted to clarify -- after this PR the entire software compilation flow is hosted in bsg_replicant right? If we want to move kernel code into replicant (as you suggested at the very beginning), it should be easy?

**Comment by mrutt92** [comment]
Yes, I left the original tests untouched and you can use any method you prefer. You can use mk/benchmark_template.mk with a few modifications and that would put the entire flow in replicant.

**Comment by yodada** [comment]
Sweet. Do you want to hit "merge"?

**Comment by mrutt92** [comment]
with pleasure

**Pull request merged**
